<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WpfLab.WpfRuntime" Version="1.0.0-local.2" />
    <PackageReference Include="AvalonEdit" Version="6.0.1" />
  </ItemGroup>
</Project>
